### ISSUE TITLE
Covermaker can't delete cover.pdf

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/covermaker#28]
Getting an error from covermaker that it can't delete the cover.pdf:

PDF CSS file: S:/resources/bookmaker_scripts/bookmaker_assets/pdfmaker/css/SMP/pdf.css
C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:1439:in `unlink': Permission denied - C:/Users/padwoadmin/Dropbox (Macmillan Publishers)/bookmaker_bot/bookmaker_egalley/submitted_images/cover.pdf (Errno::EACCES)
	from C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:1439:in `block in remove_file'
	from C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:1447:in `platform_support'
	from C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:1438:in `remove_file'
	from C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:785:in `remove_file'
	from C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:563:in `block in rm'
	from C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:562:in `each'
	from C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:562:in `rm'
	from S:/resources/bookmaker_scripts/covermaker/bookmaker_covermaker.rb:154:in `<main>'
RUNNING COVERMAKER
Generating cover.

It doesn't seem to be stopping anything, and the cover was created successfully.

**Comment by mattretzer** [comment]
we could move this bit of cleanup to cleanup.rb script in case a sluggish process or sync is keeping the file 'in use' for a couple seconds too long

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Haven't seen this since November, we may have added patch or delay for a dupe or similar issue. Closing.
