### ISSUE TITLE
Header content (from htmlmaker_js) is displayed in epub titlepages

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/covermaker#40]
I think the fix will be adding this to titlepage.css:
header {
   display: none;
}

**Comment by mattretzer** [comment]
Example manuscripts to test against: 
https://www.dropbox.com/s/obt7cr8hkkc7qwg/9780765395399_MNU.docx?dl=0
https://www.dropbox.com/s/rohh5borrahvpbq/9780765395436_MNU.docx?dl=0

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

submitted for review:
https://github.com/macmillanpublishers/covermaker/pull/41
